# Generated by Django 6.0.6 on 2026-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('price_per_gallon', models.FloatField()),
                ('geocode_source', models.CharField(max_length=20)),
            ],
        ),
    ]
